local util = require("memo.util")

describe("make_header", function()
	it("returns 4 lines", function()
		local lines = util.make_header("test.lua", "myproject")
		assert.equals(4, #lines)
	end)

	it("starts and ends with empty lines", function()
		local lines = util.make_header("test.lua", "myproject")
		assert.equals("", lines[1])
		assert.equals("", lines[4])
	end)

	it("contains separator and metadata in line 3", function()
		local lines = util.make_header("test.lua", "myproject")
		assert.equals("---", lines[2])
		assert.truthy(lines[3]:match("myproject"))
		assert.truthy(lines[3]:match("test.lua"))
	end)

	it("includes a date in YYYY-MM-DD format", function()
		local lines = util.make_header("a.lua", "proj")
		assert.truthy(lines[3]:match("%d%d%d%d%-%d%d%-%d%d"))
	end)
end)

describe("make_location", function()
	it("uses a path relative to git root with selected line range", function()
		local location = util.make_location("/repo/lua/memo/init.lua", "/repo", 12, 20)
		assert.equals("lua/memo/init.lua:12-20", location)
	end)

	it("uses a single line suffix when start and end are the same", function()
		local location = util.make_location("/repo/lua/memo/init.lua", "/repo", 12, 12)
		assert.equals("lua/memo/init.lua:12", location)
	end)

	it("keeps the full path outside git root", function()
		local location = util.make_location("/tmp/scratch.lua", "/repo", 1, 2)
		assert.equals("/tmp/scratch.lua:1-2", location)
	end)
end)

describe("make_code_block", function()
	it("wraps lines in fenced code block with filetype", function()
		local block = util.make_code_block({ "local x = 1" }, "lua")
		assert.equals("```lua", block[1])
		assert.equals("local x = 1", block[2])
		assert.equals("```", block[3])
		assert.equals("", block[4])
	end)

	it("uses empty fence when filetype is nil", function()
		local block = util.make_code_block({ "line" }, nil)
		assert.equals("```", block[1])
	end)

	it("preserves all lines", function()
		local block = util.make_code_block({ "a", "b", "c" }, "python")
		assert.equals("```python", block[1])
		assert.equals("a", block[2])
		assert.equals("b", block[3])
		assert.equals("c", block[4])
		assert.equals("```", block[5])
		assert.equals("", block[6])
	end)
end)

describe("resolve_memo_path", function()
	it("returns configured path when per_project is false", function()
		local path = util.resolve_memo_path("/repo", { per_project = false, path = "/tmp/memo.md" })
		assert.equals("/tmp/memo.md", path)
	end)

	it("returns per-project path when per_project is true and git_root exists", function()
		local path = util.resolve_memo_path("/repo", { per_project = true, path = "/tmp/memo.md" })
		assert.equals("/repo/.memo.md", path)
	end)

	it("falls back to configured path when per_project is true but git_root is nil", function()
		local path = util.resolve_memo_path(nil, { per_project = true, path = "/tmp/memo.md" })
		assert.equals("/tmp/memo.md", path)
	end)
end)
